export const headersdata = [
  { id: 1, name: 'WWW-Authenticate' },
  { id: 2, name: 'Authorization' },
  { id: 3, name: 'Cache-Control' },
  { id: 4, name: 'Connection' },
  { id: 5, name: 'Keep-Alive' },
  { id: 6, name: 'Access-Control-Allow-Origin' },
  { id: 7, name: 'Access-Control-Allow-Credentials' },
  { id: 8, name: 'Access-Control-Allow-Headers' },
  { id: 9, name: 'Access-Control-Allow-Methods' },
  { id: 10, name: 'Access-Control-Expose-Headers' },
  { id: 11, name: 'Access-Control-Max-Age' },
  { id: 12, name: 'Access-Control-Request-Headers' },
  { id: 13, name: 'Access-Control-Request-Methods' },
  { id: 14, name: 'apollo-federation-include-trace' },
  { id: 15, name: 'apollographql-client-name' },
  { id: 16, name: 'apollographql-client-version' },
];
